# Generated by Django 3.2.2 on 2022-10-22 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_Final', models.DateField()),
                ('estado', models.CharField(choices=[('Evaluado', 'Evaluado'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Enviada', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
