# Generated by Django 3.2.2 on 2022-10-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.cita'),
            preserve_default=False,
        ),
    ]
