# Generated by Django 3.2.2 on 2022-10-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_alter_material_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='materiales',
            field=models.ManyToManyField(blank=True, related_name='materials', to='proyecto.Material'),
        ),
    ]
