# Generated by Django 3.2.2 on 2022-10-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_proyecto_materiales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='user',
            new_name='cliente',
        ),
    ]
