# Generated by Django 3.2.2 on 2022-10-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_rename_user_proyecto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='materiales',
        ),
    ]
