# Generated by Django 3.2.2 on 2022-12-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_cotizacion_proyecto'),
        ('proyecto', '0011_remove_proyecto_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectoCotizado', to='cotizaciones.cotizacion'),
            preserve_default=False,
        ),
    ]
