# Generated by Django 3.2.2 on 2022-12-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_cotizacion_proyecto'),
        ('proyecto', '0012_proyecto_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectoCotizado', to='cotizaciones.cotizacion'),
        ),
    ]
