# Generated by Django 3.2.2 on 2023-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_alter_proyecto_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
