# Generated by Django 3.2.2 on 2022-10-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion_material',
            options={'verbose_name': 'Asignacion_Material', 'verbose_name_plural': 'Asignacion_Materiales'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
