# Generated by Django 3.2.2 on 2022-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_auto_20221209_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
