# Generated by Django 3.2.2 on 2022-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_material_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
