# Generated by Django 3.2.2 on 2022-10-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
