# Generated by Django 3.2.2 on 2022-10-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221022_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
