# Generated by Django 3.2.2 on 2022-10-22 22:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221022_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='users/user_default_bg.jpg', upload_to=accounts.models.user_directory_path_banner),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.png', upload_to=accounts.models.user_directory_path_profile),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
