# Generated by Django 3.2.2 on 2022-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221022_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
