# Generated by Django 3.2.2 on 2022-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
