# Generated by Django 3.2.2 on 2022-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
