# Generated by Django 3.2.2 on 2022-10-22 03:24

from django.db import migrations, models
import empleados.models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacion_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='users/user_default_profile.png', upload_to=empleados.models.user_directory_path_empleado),
        ),
    ]
