# Generated by Django 3.2.2 on 2022-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_auto_20221202_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
