# Generated by Django 3.2.2 on 2022-11-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
